# Generated by Django 4.2.7 on 2023-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, max_length=221, null=True, unique=True),
        ),
    ]
