# Generated by Django 4.2.7 on 2024-01-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Gram'), (2, 'Litre'), (3, 'Piece')], default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
